<?php
/**
  * Implementation of hook_menu().
  */
function jstree_menu() {
   $items['jstree'] = array(
      'title' => 'Jstree', 
      'description' => 'Jstree',
      'page callback' => 'jstree_render',
      'access arguments' => array('access content'),
      'type' => MENU_NORMAL_ITEM,
    //  'file' => 'siamensis_hooker_admin.inc',
      'file'=> 'jstree_render.inc',
   );
   $items['json'] = array(
      'title' => 'Json', 
      'description' => 'Jsone',
      'page callback' => 'json',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
      'file'=> 'jstree_render.inc',
   );
  $items['jstree/node/%node'] = array(
    'page callback' => 'jstree_node',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file'=> 'jstree_render.inc',
  );
  
  $items['admin/settings/jstree'] = array(
    'title' => 'Jstree settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jstree_admin_settings'),
    'access arguments' => array('administer nodes'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'jstree.admin.inc',
  );
 
   return $items;
}

